import 'dart:async';
import 'dart:ui';

import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_secure_storage/flutter_secure_storage.dart';

final localeProvider = NotifierProvider<LocaleController, Locale>(
  LocaleController.new,
);

class LocaleController extends Notifier<Locale> {
  static const _storage = FlutterSecureStorage();
  bool _loading = false;

  @override
  Locale build() {
    if (!_loading) {
      _loading = true;
      unawaited(_restore());
    }
    final system = PlatformDispatcher.instance.locale.languageCode;
    return Locale(system == 'ar' ? 'ar' : 'en');
  }

  Future<void> _restore() async {
    final saved = await _storage.read(key: 'locale');
    if (saved == 'ar' || saved == 'en') state = Locale(saved!);
  }

  void toggle() => setLocale(state.languageCode == 'en' ? 'ar' : 'en');
  void setLocale(String code) {
    final normalized = code == 'ar' ? 'ar' : 'en';
    state = Locale(normalized);
    unawaited(_storage.write(key: 'locale', value: normalized));
  }
}

const _en = <String, String>{
  'welcome': 'Welcome',
  'login': 'Log in',
  'register': 'Create account',
  'email': 'Email',
  'password': 'Password',
  'forgot': 'Forgot password?',
  'home': 'Home',
  'shop': 'Shop',
  'categories': 'Categories',
  'new': 'New arrivals',
  'offers': 'Offers',
  'search': 'Search products, brands or SKU',
  'bag': 'Bag',
  'favorites': 'Wishlist',
  'account': 'Account',
  'profile': 'Profile',
  'orders': 'Orders',
  'returns': 'Returns',
  'notifications': 'Notifications',
  'addresses': 'Addresses',
  'security': 'Security',
  'settings': 'Settings',
  'language': 'Language',
  'viewAll': 'View all',
  'retry': 'Try again',
  'empty': 'Nothing here yet',
  'addToBag': 'Add to bag',
  'checkout': 'Checkout',
  'coupon': 'Coupon code',
  'apply': 'Apply',
  'subtotal': 'Subtotal',
  'discount': 'Discount',
  'shipping': 'Shipping',
  'tax': 'VAT (15%)',
  'total': 'Total',
  'confirmOrder': 'Confirm order',
  'deliveryAddress': 'Delivery address',
  'deliveryOption': 'Delivery option',
  'paymentMethod': 'Payment method',
  'orderSuccess': 'Order placed successfully',
  'trackOrder': 'Track order',
  'orderTracking': 'Order tracking',
  'contact': 'Contact support',
  'editProfile': 'Edit profile',
  'changePassword': 'Change password',
  'sessions': 'Active sessions',
  'about': 'About MARINA',
  'privacy': 'Privacy policy',
  'terms': 'Terms & conditions',
  'help': 'Help & support',
  'logout': 'Log out',
  'admin': 'Admin',
  'dashboard': 'Dashboard',
  'products': 'Products',
  'inventory': 'Inventory',
  'customers': 'Customers',
  'coupons': 'Coupons',
  'reports': 'Reports',
  'usersRoles': 'Users & roles',
  'audit': 'Audit logs',
  'lowStock': 'Low stock',
  'recentOrders': 'Recent orders',
  'sales': 'Sales',
  'addProduct': 'Add product',
  'editProduct': 'Edit product',
  'save': 'Save',
  'cancel': 'Cancel',
  'close': 'Close',
  'remove': 'Remove',
  'continueShopping': 'Continue shopping',
  'noInternet': 'No internet connection',
  'maintenance': 'MARINA is temporarily unavailable',
  'loading': 'Preparing MARINA',
  'sortFilter': 'Sort & filter',
  'brands': 'Brands',
  'colors': 'Colors',
  'sizes': 'Sizes',
  'reviews': 'Reviews',
  'related': 'You may also like',
  'chooseVariant': 'Choose color and size',
  'outOfStock': 'Out of stock',
  'verifiedReviews': 'verified reviews',
  'writeReview': 'Write a review',
  'noReviews': 'No approved reviews yet',
  'verifiedPurchase': 'Verified purchase',
  'reviewTooShort': 'Please write at least 10 characters.',
  'reviewTitle': 'Review title (optional)',
  'reviewBody': 'Tell us about the product',
  'submitForReview': 'Submit for moderation',
  'items': 'items',
  'orderNumber': 'Order number',
  'requestReturn': 'Request a return',
  'selectReturnItems': 'Choose at least one item and enter a reason.',
  'returnSubmitted': 'Return request submitted',
  'chooseItems': 'Choose items to return',
  'returnReason': 'Reason for return',
  'additionalDetails': 'Additional details (optional)',
  'submitReturn': 'Submit return request',
  'adminReturns': 'Returns',
  'adminReviews': 'Review moderation',
  'queueEmpty': 'This queue is clear',
  'approve': 'Approve',
  'reject': 'Reject',
  'markReceived': 'Mark as received',
  'requestRefund': 'Request provider refund',
  'fullName': 'Full name',
  'phone': 'Phone number',
  'addAddress': 'Add address',
  'editAddress': 'Edit address',
  'defaultAddress': 'Default',
  'edit': 'Edit',
  'label': 'Label',
  'recipient': 'Recipient',
  'city': 'City',
  'line1': 'Address line',
  'postalCode': 'Postal code',
  'setDefault': 'Set as default address',
  'requiredFields': 'Complete all required fields.',
  'readAll': 'Read all',
  'cashOnDelivery': 'Cash on delivery',
  'onlineUnavailable':
      'Online payment is unavailable until a provider is configured.',
  'referenceData': 'Catalog reference data',
  'savedSuccessfully': 'Saved successfully',
  'confirm': 'Confirm',
  'users': 'Users',
  'rolesPermissions': 'Roles & permissions',
  'permissions': 'permissions',
  'accountActive': 'Account active',
  'activeSession': 'Active session',
  'revoke': 'Revoke',
  'returnDetails': 'Return details',
  'returnTimeline': 'Return timeline',
  'adminNote': 'Admin note',
  'viewOrder': 'View order',
  'statusRequested': 'Requested',
  'statusApproved': 'Approved',
  'statusRejected': 'Rejected',
  'statusReceived': 'Received',
  'statusRefunded': 'Refunded',
  'statusCancelled': 'Cancelled',
  'newest': 'Newest',
  'priceLowHigh': 'Price: low to high',
  'priceHighLow': 'Price: high to low',
  'name': 'Name',
  'filters': 'Filters',
  'all': 'All',
  'minimumPrice': 'Minimum price',
  'maximumPrice': 'Maximum price',
  'clearFilters': 'Clear filters',
  'statusRefundPending': 'Refund pending',
  'add': 'Add',
  'category': 'category',
  'brand': 'brand',
  'color': 'color',
  'size': 'size',
  'slug': 'Slug',
  'code': 'Code',
  'englishName': 'English name',
  'arabicName': 'Arabic name',
  'parentCategory': 'Parent category',
  'none': 'None',
  'hexColor': 'Hex color',
  'sortOrder': 'Sort order',
  'active': 'Active',
  'adminNoteOptional': 'Admin note (optional)',
  'details': 'Details',
  'welcomeSubtitle': 'Timeless styles for the whole family.',
  'signInFailed': 'Unable to sign in.',
  'registerFailed': 'Unable to create the account.',
  'passwordRequirements': '12+ characters with upper, lower, number and symbol',
  'requestFailed': 'Unable to submit the request.',
  'forgotPassword': 'Forgot password',
  'forgotInstructions': 'Enter your email. If an account exists, reset instructions will be sent.',
  'requestAccepted': 'Request accepted. Check your configured email channel.',
  'sendInstructions': 'Send instructions',
  'haveResetToken': 'I already have a reset token',
  'invalidResetToken': 'The reset token is invalid or expired.',
  'resetPassword': 'Reset password',
  'resetToken': 'Reset token',
  'newPassword': 'New password',
  'invalidVerificationToken': 'The verification token is invalid.',
  'resendFailed': 'Unable to resend verification.',
  'verifyAccount': 'Verify your account',
  'verificationToken': 'Verification token',
  'verify': 'Verify',
  'resendVerification': 'Resend verification',
  'changePasswordFailed': 'Unable to change the password.',
  'currentPassword': 'Current password',
  'saveRecoveryCodes': 'Save recovery codes',
  'savedRecoveryCodes': 'I saved them',
  'invalidSecurityCode': 'The security code is invalid or expired.',
  'setupSecurityVerification': 'Set up security verification',
  'securityVerification': 'Security verification',
  'mfaSetupInstructions': 'Add this key to your authenticator app, then enter the generated six-digit code.',
  'mfaCodeInstructions': 'Enter the six-digit code from your authenticator app or a recovery code.',
  'securityCode': 'Security code',
  'twoFactorAuthentication': 'Two-factor authentication',
  'twoFactorDescription':
      'Required and configured during sign-in for staff accounts.',
  'english': 'English',
  'aboutBody': 'MARINA is a modern family fashion destination for thoughtfully selected clothing, shoes and accessories.',
  'privacyBody': 'MARINA processes account and order information only to provide and secure the shopping service.',
  'termsBody': 'These terms explain ordering, delivery, cancellation, returns and acceptable use of MARINA services.',
  'helpBody': 'Our customer care team can help with products, delivery, returns and account security.',
  'orderSubmissionFailed': 'Order submission failed. You can retry safely.',
  'standardDeliveryFree': 'Standard delivery — free',
  'standardDelivery': 'Standard delivery',
  'cashOnDeliveryDescription': 'Pay when your order is delivered.',
  'onlinePayment': 'Online payment',
  'searchPrompt': 'Search by product, brand or SKU',
  'administrator': 'Administrator',
  'mfaProtectedSession': 'MFA protected session',
  'totalSales': 'Total sales',
  'newCustomers': 'New customers',
  'averageOrder': 'Average order',
  'quantityChange': 'Quantity change',
  'reason': 'Reason',
  'cancelOrder': 'Cancel order',
  'editCoupon': 'Edit coupon',
  'value': 'Value',
  'deactivateProduct': 'Deactivate product',
  'revenue': 'Revenue',
  'bestSellers': 'Best sellers',
  'orderStatuses': 'Order statuses',
  'noDataForPeriod': 'No data for this period.',
  'loadProductFailed': 'Unable to load the product.',
  'saveProductFailed': 'Unable to save the product.',
  'addVariant': 'Add variant',
  'editVariant': 'Edit variant',
  'sku': 'SKU',
  'barcode': 'Barcode',
  'price': 'Price',
  'compareAtPrice': 'Compare-at price',
  'initialStock': 'Initial stock',
  'deactivateVariant': 'Deactivate variant',
  'deactivateVariantMessage': 'Existing order history is preserved. The variant will no longer be sold.',
  'removeImageQuestion': 'Remove image?',
  'removeImageMessage':
      'The stored image will be deleted and cannot be restored.',
  'englishDescription': 'English description',
  'arabicDescription': 'Arabic description',
  'loadCategoriesFailed': 'Unable to load categories.',
  'featured': 'Featured',
  'newArrival': 'New arrival',
  'offer': 'Offer',
  'initialVariant': 'Initial variant',
  'variants': 'Variants',
  'productImages': 'Product images',
  'uploadImage': 'Upload image',
  'noProductImages': 'No product images uploaded.',
  'stock': 'Stock',
  'inactive': 'Inactive',
  'productImage': 'Product image',
  'position': 'Position',
  'invalidCoupon': 'Enter a code and a percentage from 0 to 100.',
  'createCouponFailed': 'Unable to create the coupon.',
  'createCoupon': 'Create coupon',
  'discountPercentage': 'Discount percentage',
  'settingKey': 'Setting key',
  'publicAppSetting': 'Expose in public app configuration',
  'moveTo': 'Move to',
  'unknown': 'Unknown',
  'statusPending': 'Pending',
  'statusConfirmed': 'Confirmed',
  'statusPreparing': 'Preparing',
  'statusReady': 'Ready',
  'statusShipped': 'Shipped',
  'statusOutForDelivery': 'Out for delivery',
  'statusDelivered': 'Delivered',
  'statusReturned': 'Returned',
  'adjust': 'Adjust',
  'movementHistory': 'Movement history',
  'discountType': 'Discount type',
  'percentage': 'Percentage',
  'fixedAmount': 'Fixed amount',
  'minimumPurchase': 'Minimum purchase (optional)',
  'maximumDiscount': 'Maximum discount (optional)',
  'maxUses': 'Maximum uses (optional)',
  'maxUsesPerCustomer': 'Uses per customer (optional)',
  'validFrom': 'Valid from',
  'validTo': 'Valid to',
  'couponUsage': 'Recorded uses',
  'cancelOrderConfirmation':
      'Cancel this order? Reserved inventory will be released.',
  'customerCancellation': 'Cancelled by customer',
  'sessionExpiredMessage': 'Your session expired. Please sign in again.',
  'securityEvents': 'Security events',
  'manageNotifications': 'Customer notifications',
  'inAppNotificationDescription': 'Send a real in-app notification. Email, SMS and push remain disabled until their providers are configured.',
  'customer': 'Customer',
  'notificationTitle': 'Notification title',
  'notificationBody': 'Notification message',
  'deepLinkOptional': 'App deep link (optional)',
  'sendNotification': 'Send notification',
  'notificationHistory': 'Notification history',
  'notificationSent': 'Notification sent',
  'page': 'Page',
  'previousPage': 'Previous page',
  'nextPage': 'Next page',
  'appearance': 'Appearance',
  'appearanceSubtitle': 'Choose how MARINA looks — day, night, or follow your system automatically.',
  'themeSystem': 'System',
  'themeSystemHint': 'Follow your device appearance automatically',
  'themeLight': 'Day',
  'themeLightHint': 'Warm ivory & deep navy',
  'themeDark': 'Night',
  'themeDarkHint': 'Midnight navy & champagne gold',
  'recommended': 'Recommended',
  'free': 'Free',
  'emptyBag': 'Your bag is empty',
  'emptyWishlist': 'Your wishlist is empty',
  'sectionPreferences': 'Preferences',
  'sectionSupport': 'Help & information',
};

const _ar = <String, String>{
  'welcome': 'مرحبًا',
  'login': 'تسجيل الدخول',
  'register': 'إنشاء حساب',
  'email': 'البريد الإلكتروني',
  'password': 'كلمة المرور',
  'forgot': 'نسيت كلمة المرور؟',
  'home': 'الرئيسية',
  'shop': 'تسوّق',
  'categories': 'الفئات',
  'new': 'وصل حديثًا',
  'offers': 'العروض',
  'search': 'ابحث عن منتج أو علامة أو رمز SKU',
  'bag': 'السلة',
  'favorites': 'المفضلة',
  'account': 'الحساب',
  'profile': 'الملف الشخصي',
  'orders': 'الطلبات',
  'returns': 'المرتجعات',
  'notifications': 'الإشعارات',
  'addresses': 'العناوين',
  'security': 'الأمان',
  'settings': 'الإعدادات',
  'language': 'اللغة',
  'viewAll': 'عرض الكل',
  'retry': 'إعادة المحاولة',
  'empty': 'لا توجد بيانات بعد',
  'addToBag': 'أضف إلى السلة',
  'checkout': 'إتمام الطلب',
  'coupon': 'رمز القسيمة',
  'apply': 'تطبيق',
  'subtotal': 'المجموع الفرعي',
  'discount': 'الخصم',
  'shipping': 'الشحن',
  'tax': 'ضريبة القيمة المضافة (15٪)',
  'total': 'الإجمالي',
  'confirmOrder': 'تأكيد الطلب',
  'deliveryAddress': 'عنوان التوصيل',
  'deliveryOption': 'خيار التوصيل',
  'paymentMethod': 'طريقة الدفع',
  'orderSuccess': 'تم إنشاء الطلب بنجاح',
  'trackOrder': 'تتبّع الطلب',
  'orderTracking': 'تتبّع الطلب',
  'contact': 'تواصل مع الدعم',
  'editProfile': 'تعديل الملف الشخصي',
  'changePassword': 'تغيير كلمة المرور',
  'sessions': 'الجلسات النشطة',
  'about': 'عن مارينا',
  'privacy': 'سياسة الخصوصية',
  'terms': 'الشروط والأحكام',
  'help': 'المساعدة والدعم',
  'logout': 'تسجيل الخروج',
  'admin': 'الإدارة',
  'dashboard': 'لوحة التحكم',
  'products': 'المنتجات',
  'inventory': 'المخزون',
  'customers': 'العملاء',
  'coupons': 'القسائم',
  'reports': 'التقارير',
  'usersRoles': 'المستخدمون والأدوار',
  'audit': 'سجل التدقيق',
  'lowStock': 'مخزون منخفض',
  'recentOrders': 'أحدث الطلبات',
  'sales': 'المبيعات',
  'addProduct': 'إضافة منتج',
  'editProduct': 'تعديل المنتج',
  'save': 'حفظ',
  'cancel': 'إلغاء',
  'close': 'إغلاق',
  'remove': 'إزالة',
  'continueShopping': 'متابعة التسوق',
  'noInternet': 'لا يوجد اتصال بالإنترنت',
  'maintenance': 'مارينا غير متاحة مؤقتًا',
  'loading': 'جارٍ تجهيز مارينا',
  'sortFilter': 'الترتيب والتصفية',
  'brands': 'العلامات التجارية',
  'colors': 'الألوان',
  'sizes': 'المقاسات',
  'reviews': 'التقييمات',
  'related': 'قد يعجبك أيضًا',
  'chooseVariant': 'اختر اللون والمقاس',
  'outOfStock': 'غير متوفر',
  'verifiedReviews': 'تقييمات موثقة',
  'writeReview': 'اكتب تقييمًا',
  'noReviews': 'لا توجد تقييمات معتمدة بعد',
  'verifiedPurchase': 'عملية شراء موثقة',
  'reviewTooShort': 'اكتب عشرة أحرف على الأقل.',
  'reviewTitle': 'عنوان التقييم (اختياري)',
  'reviewBody': 'أخبرنا عن تجربتك مع المنتج',
  'submitForReview': 'إرسال للمراجعة',
  'items': 'منتجات',
  'orderNumber': 'رقم الطلب',
  'requestReturn': 'طلب إرجاع',
  'selectReturnItems': 'اختر منتجًا واحدًا على الأقل وأدخل السبب.',
  'returnSubmitted': 'تم إرسال طلب الإرجاع',
  'chooseItems': 'اختر المنتجات المراد إرجاعها',
  'returnReason': 'سبب الإرجاع',
  'additionalDetails': 'تفاصيل إضافية (اختياري)',
  'submitReturn': 'إرسال طلب الإرجاع',
  'adminReturns': 'المرتجعات',
  'adminReviews': 'مراجعة التقييمات',
  'queueEmpty': 'لا توجد عناصر بانتظار الإجراء',
  'approve': 'موافقة',
  'reject': 'رفض',
  'markReceived': 'تأكيد الاستلام',
  'requestRefund': 'طلب رد المبلغ من المزوّد',
  'fullName': 'الاسم الكامل',
  'phone': 'رقم الهاتف',
  'addAddress': 'إضافة عنوان',
  'editAddress': 'تعديل العنوان',
  'defaultAddress': 'الافتراضي',
  'edit': 'تعديل',
  'label': 'اسم العنوان',
  'recipient': 'اسم المستلم',
  'city': 'المدينة',
  'line1': 'تفاصيل العنوان',
  'postalCode': 'الرمز البريدي',
  'setDefault': 'تعيين كعنوان افتراضي',
  'requiredFields': 'أكمل جميع الحقول المطلوبة.',
  'readAll': 'قراءة الكل',
  'cashOnDelivery': 'الدفع عند الاستلام',
  'onlineUnavailable': 'الدفع الإلكتروني غير متاح حتى تتم تهيئة مزوّد دفع.',
  'referenceData': 'بيانات الكتالوج المرجعية',
  'savedSuccessfully': 'تم الحفظ بنجاح',
  'confirm': 'تأكيد',
  'users': 'المستخدمون',
  'rolesPermissions': 'الأدوار والصلاحيات',
  'permissions': 'صلاحيات',
  'accountActive': 'الحساب نشط',
  'activeSession': 'جلسة نشطة',
  'revoke': 'إلغاء الجلسة',
  'returnDetails': 'تفاصيل المرتجع',
  'returnTimeline': 'مراحل المرتجع',
  'adminNote': 'ملاحظة الإدارة',
  'viewOrder': 'عرض الطلب',
  'statusRequested': 'تم الطلب',
  'statusApproved': 'تمت الموافقة',
  'statusRejected': 'مرفوض',
  'statusReceived': 'تم الاستلام',
  'statusRefunded': 'تم رد المبلغ',
  'statusCancelled': 'ملغي',
  'newest': 'الأحدث',
  'priceLowHigh': 'السعر: من الأقل إلى الأعلى',
  'priceHighLow': 'السعر: من الأعلى إلى الأقل',
  'name': 'الاسم',
  'filters': 'التصفية',
  'all': 'الكل',
  'minimumPrice': 'أقل سعر',
  'maximumPrice': 'أعلى سعر',
  'clearFilters': 'مسح التصفية',
  'statusRefundPending': 'بانتظار رد المبلغ',
  'add': 'إضافة',
  'category': 'فئة',
  'brand': 'علامة تجارية',
  'color': 'لون',
  'size': 'مقاس',
  'slug': 'المعرّف النصي',
  'code': 'الرمز',
  'englishName': 'الاسم بالإنجليزية',
  'arabicName': 'الاسم بالعربية',
  'parentCategory': 'الفئة الأب',
  'none': 'بلا',
  'hexColor': 'رمز اللون',
  'sortOrder': 'ترتيب العرض',
  'active': 'نشط',
  'adminNoteOptional': 'ملاحظة الإدارة (اختياري)',
  'details': 'التفاصيل',
  'welcomeSubtitle': 'أناقة خالدة لكل أفراد العائلة.',
  'signInFailed': 'تعذر تسجيل الدخول.',
  'registerFailed': 'تعذر إنشاء الحساب.',
  'passwordRequirements': '12 حرفًا على الأقل مع حرف كبير وصغير ورقم ورمز',
  'requestFailed': 'تعذر إرسال الطلب.',
  'forgotPassword': 'نسيت كلمة المرور',
  'forgotInstructions': 'أدخل بريدك الإلكتروني، وستُرسل تعليمات الاستعادة إذا كان الحساب موجودًا.',
  'requestAccepted': 'تم قبول الطلب. راجع قناة البريد الإلكتروني المهيأة.',
  'sendInstructions': 'إرسال التعليمات',
  'haveResetToken': 'لدي رمز استعادة بالفعل',
  'invalidResetToken': 'رمز الاستعادة غير صالح أو منتهي الصلاحية.',
  'resetPassword': 'إعادة تعيين كلمة المرور',
  'resetToken': 'رمز الاستعادة',
  'newPassword': 'كلمة المرور الجديدة',
  'invalidVerificationToken': 'رمز التحقق غير صالح.',
  'resendFailed': 'تعذر إعادة إرسال التحقق.',
  'verifyAccount': 'التحقق من الحساب',
  'verificationToken': 'رمز التحقق',
  'verify': 'تحقق',
  'resendVerification': 'إعادة إرسال التحقق',
  'changePasswordFailed': 'تعذر تغيير كلمة المرور.',
  'currentPassword': 'كلمة المرور الحالية',
  'saveRecoveryCodes': 'احفظ رموز الاسترداد',
  'savedRecoveryCodes': 'حفظت الرموز',
  'invalidSecurityCode': 'رمز الأمان غير صالح أو منتهي الصلاحية.',
  'setupSecurityVerification': 'إعداد التحقق الأمني',
  'securityVerification': 'التحقق الأمني',
  'mfaSetupInstructions':
      'أضف هذا المفتاح إلى تطبيق المصادقة ثم أدخل الرمز المكون من ستة أرقام.',
  'mfaCodeInstructions':
      'أدخل الرمز المكون من ستة أرقام من تطبيق المصادقة أو أحد رموز الاسترداد.',
  'securityCode': 'رمز الأمان',
  'twoFactorAuthentication': 'المصادقة الثنائية',
  'twoFactorDescription':
      'مطلوبة لحسابات الموظفين ويتم إعدادها أثناء تسجيل الدخول.',
  'english': 'English',
  'aboutBody': 'مارينا وجهة عصرية لأزياء العائلة، تقدم مختارات مدروسة من الملابس والأحذية والإكسسوارات.',
  'privacyBody':
      'تعالج مارينا بيانات الحساب والطلب فقط لتقديم خدمة التسوق وحمايتها.',
  'termsBody': 'توضح هذه الشروط آلية الطلب والتوصيل والإلغاء والإرجاع والاستخدام المقبول لخدمات مارينا.',
  'helpBody': 'يمكن لفريق خدمة العملاء مساعدتك في المنتجات والتوصيل والمرتجعات وأمان الحساب.',
  'orderSubmissionFailed': 'تعذر إرسال الطلب. يمكنك إعادة المحاولة بأمان.',
  'standardDeliveryFree': 'توصيل قياسي — مجانًا',
  'standardDelivery': 'توصيل قياسي',
  'cashOnDeliveryDescription': 'ادفع عند استلام طلبك.',
  'onlinePayment': 'الدفع الإلكتروني',
  'searchPrompt': 'ابحث باسم المنتج أو العلامة أو رمز SKU',
  'administrator': 'المسؤول',
  'mfaProtectedSession': 'جلسة محمية بالمصادقة الثنائية',
  'totalSales': 'إجمالي المبيعات',
  'newCustomers': 'العملاء الجدد',
  'averageOrder': 'متوسط الطلب',
  'quantityChange': 'تغيير الكمية',
  'reason': 'السبب',
  'cancelOrder': 'إلغاء الطلب',
  'editCoupon': 'تعديل القسيمة',
  'value': 'القيمة',
  'deactivateProduct': 'إلغاء تنشيط المنتج',
  'revenue': 'الإيرادات',
  'bestSellers': 'الأكثر مبيعًا',
  'orderStatuses': 'حالات الطلبات',
  'noDataForPeriod': 'لا توجد بيانات لهذه الفترة.',
  'loadProductFailed': 'تعذر تحميل المنتج.',
  'saveProductFailed': 'تعذر حفظ المنتج.',
  'addVariant': 'إضافة متغير',
  'editVariant': 'تعديل المتغير',
  'sku': 'رمز SKU',
  'barcode': 'الباركود',
  'price': 'السعر',
  'compareAtPrice': 'السعر قبل الخصم',
  'initialStock': 'المخزون الأولي',
  'deactivateVariant': 'إلغاء تنشيط المتغير',
  'deactivateVariantMessage':
      'سيبقى سجل الطلبات محفوظًا، ولن يعود هذا المتغير متاحًا للبيع.',
  'removeImageQuestion': 'إزالة الصورة؟',
  'removeImageMessage': 'ستُحذف الصورة المخزنة ولا يمكن استعادتها.',
  'englishDescription': 'الوصف بالإنجليزية',
  'arabicDescription': 'الوصف بالعربية',
  'loadCategoriesFailed': 'تعذر تحميل الفئات.',
  'featured': 'مميز',
  'newArrival': 'وصل حديثًا',
  'offer': 'عرض',
  'initialVariant': 'المتغير الأولي',
  'variants': 'المتغيرات',
  'productImages': 'صور المنتج',
  'uploadImage': 'رفع صورة',
  'noProductImages': 'لم تُرفع صور للمنتج.',
  'stock': 'المخزون',
  'inactive': 'غير نشط',
  'productImage': 'صورة المنتج',
  'position': 'الموضع',
  'invalidCoupon': 'أدخل رمزًا ونسبة خصم من 0 إلى 100.',
  'createCouponFailed': 'تعذر إنشاء القسيمة.',
  'createCoupon': 'إنشاء قسيمة',
  'discountPercentage': 'نسبة الخصم',
  'settingKey': 'مفتاح الإعداد',
  'publicAppSetting': 'إظهاره في إعدادات التطبيق العامة',
  'moveTo': 'نقل إلى',
  'unknown': 'غير معروف',
  'statusPending': 'قيد الانتظار',
  'statusConfirmed': 'مؤكد',
  'statusPreparing': 'قيد التجهيز',
  'statusReady': 'جاهز',
  'statusShipped': 'تم الشحن',
  'statusOutForDelivery': 'خرج للتوصيل',
  'statusDelivered': 'تم التسليم',
  'statusReturned': 'تم الإرجاع',
  'adjust': 'تعديل',
  'movementHistory': 'سجل الحركات',
  'discountType': 'نوع الخصم',
  'percentage': 'نسبة مئوية',
  'fixedAmount': 'مبلغ ثابت',
  'minimumPurchase': 'الحد الأدنى للشراء (اختياري)',
  'maximumDiscount': 'الحد الأقصى للخصم (اختياري)',
  'maxUses': 'أقصى عدد استخدامات (اختياري)',
  'maxUsesPerCustomer': 'الاستخدامات لكل عميل (اختياري)',
  'validFrom': 'صالح من',
  'validTo': 'صالح حتى',
  'couponUsage': 'مرات الاستخدام المسجلة',
  'cancelOrderConfirmation': 'هل تريد إلغاء هذا الطلب؟ سيُعاد المخزون المحجوز.',
  'customerCancellation': 'أُلغي بواسطة العميل',
  'sessionExpiredMessage': 'انتهت جلستك. سجّل الدخول مرة أخرى.',
  'securityEvents': 'أحداث الأمان',
  'manageNotifications': 'إشعارات العملاء',
  'inAppNotificationDescription': 'أرسل إشعارًا حقيقيًا داخل التطبيق. تبقى خدمات البريد والرسائل القصيرة والإشعارات الفورية معطلة حتى تهيئة مزوديها.',
  'customer': 'العميل',
  'notificationTitle': 'عنوان الإشعار',
  'notificationBody': 'نص الإشعار',
  'deepLinkOptional': 'رابط داخل التطبيق (اختياري)',
  'sendNotification': 'إرسال الإشعار',
  'notificationHistory': 'سجل الإشعارات',
  'notificationSent': 'تم إرسال الإشعار',
  'page': 'الصفحة',
  'previousPage': 'الصفحة السابقة',
  'nextPage': 'الصفحة التالية',
  'appearance': 'المظهر',
  'appearanceSubtitle': 'اختر شكل مارينا — نهاري أو ليلي أو حسب إعداد جهازك تلقائيًا.',
  'themeSystem': 'حسب النظام',
  'themeSystemHint': 'يتبع مظهر جهازك تلقائيًا',
  'themeLight': 'نهاري',
  'themeLightHint': 'عاجي دافئ وكحلي عميق',
  'themeDark': 'ليلي',
  'themeDarkHint': 'كحلي منتصف الليل وذهبي شمبانيا',
  'recommended': 'مختارات لك',
  'free': 'مجانًا',
  'emptyBag': 'سلتك فارغة',
  'emptyWishlist': 'قائمة مفضلتك فارغة',
  'sectionPreferences': 'التفضيلات',
  'sectionSupport': 'الدعم والمعلومات',
};

extension MarinaStrings on BuildContext {
  String tr(String key) {
    final code = Localizations.localeOf(this).languageCode;
    return (code == 'ar' ? _ar : _en)[key] ?? key;
  }
}
